name: dotube
description: "A docabs project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_desktop_tools:
    git:
      url: https://github.com/KRTirtho/flutter_desktop_tools.git
      ref: 1f0bec3283626dcbd8ee2f54e238d096d8dea50e
  timezone: ^0.9.3
  system_theme: ^2.3.1
  shared_preferences: ^2.2.3
  catcher_2: ^1.2.6
  flutter_riverpod: ^2.5.1
  device_preview: ^1.1.0
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  riverpod: ^2.5.1
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  fluentui_system_icons: ^1.1.244
  flutter_feather_icons: ^2.0.0+1
  simple_icons: ^10.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  sidebarx: ^0.17.1
  collection: ^1.18.0
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  logger: ^2.3.0
  bonsoir: ^5.1.9
  device_info_plus: ^10.1.0
  uuid: ^3.0.7
  skeletonizer: ^1.3.0
  spotify:
    git:
      url: https://github.com/KRTirtho/spotify-dart.git
      ref: fix/explicit-to-json
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  flutter_inappwebview: ^6.0.0
  flutter_secure_storage: ^9.2.0
  hive: ^2.2.3
  envied: ^0.5.4+1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  path: ^1.9.0
  window_manager: ^0.3.9
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.5.0+1
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.5.2

dependency_overrides:
  uuid: ^4.4.0
  system_tray:
    # TODO: remove this when flutter_desktop_tools gets updated
    # to use [MenuItemBase] instead of [MenuItem]
    git:
      url: https://github.com/antler119/system_tray
      ref: dc7ef410d5cfec897edf060c1c4baff69f7c181c
  # media_kit_native_event_loop: # to fix "macro name must be an identifier"
  #   git:
  #     url: https://github.com/media-kit/media-kit
  #     path: media_kit_native_event_loop
  #     ref: main

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/configs